---
swagger: "2.0"
info:
  version: "1.0.0"
  title: ""
host: "localhost:8080"
basePath: "/eight/api"
schemes:
- "http"
paths:
  /movies:
    get:
      operationId: "moviesByTitle"
      parameters:
      - name: "title"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Movie"
          headers: {}
    post:
      operationId: "insertMovie"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Movie"
      responses:
        default:
          description: "successful operation"
  /movies/{id}:
    put:
      operationId: "updateMovie"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Movie"
      responses:
        default:
          description: "successful operation"
    delete:
      operationId: "deleteMovie"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        default:
          description: "successful operation"
  /movies/{id}/actions/updateUri:
    post:
      operationId: "updateMovieUri"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "string"
      responses:
        default:
          description: "successful operation"
  /osoby:
    get:
      operationId: "getPeople"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /people:
    get:
      operationId: "people"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Person"
          headers: {}
    post:
      operationId: "insertPerson"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Person"
      responses:
        default:
          description: "successful operation"
  /people/{id}:
    get:
      operationId: "getPerson"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        default:
          description: "successful operation"
    put:
      operationId: "updatePerson"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Person"
      responses:
        default:
          description: "successful operation"
    delete:
      operationId: "deletePerson"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        default:
          description: "successful operation"
  /people/{id}/avatar:
    get:
      operationId: "getPersonAvatar"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        default:
          description: "successful operation"
  /people/{id}/downloadableAvatar:
    get:
      operationId: "getPersonDownloadableAvatar"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        default:
          description: "successful operation"
  /people/{id}/movies:
    get:
      operationId: "getPersonMovies"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        default:
          description: "successful operation"
definitions:
  Movie:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      uri:
        type: "string"
      persons:
        type: "array"
        items:
          $ref: "#/definitions/Person"
  StreamingOutput:
    type: "object"
  Person:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      age:
        type: "integer"
        format: "int32"
      image:
        type: "array"
        items:
          type: "string"
          format: "byte"
      favouriteMovies:
        type: "array"
      imageStreamingOutput:
        $ref: "#/definitions/StreamingOutput"
